---
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
extends: default
rules:
  document-start: disable
  comments-indentation: disable
  braces:
    max-spaces-inside-empty: 2
  line-length:
    max: 120
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  brackets:
    max-spaces-inside: 1
